# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b06d5b5b95afc008e97c33e8cd5c67c"
name = "ratingapp"
handle = "ratingapp-1"
application_url = "https://fewer-screensaver-sheets-demonstrate.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fewer-screensaver-sheets-demonstrate.trycloudflare.com/auth/callback",
  "https://fewer-screensaver-sheets-demonstrate.trycloudflare.com/auth/shopify/callback",
  "https://fewer-screensaver-sheets-demonstrate.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
